# Generated by Django 3.1.1 on 2020-09-11 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20200911_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 0, 19, 19, 350015)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 0, 19, 19, 350015)),
        ),
    ]
